[package]
name = "nobodywho"
version = "4.6.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[build-dependencies]
cmake = "0.1"

[dependencies]
encoding_rs = "0.8.34"
godot = { git = "https://github.com/godot-rust/gdext", branch = "master", features = [
    "experimental-threads",
    "register-docs",
] }
rusqlite = { version = "0.32.1", features = ["bundled"] }
sqlite-vec = "0.1.5"
thiserror = "2.0.3"
minijinja = { version = "2.5.0", features = ["builtins", "json", "loader"] }
serde = { version = "1.0.215", features = ["derive"] }
chrono = "0.4.39"
llama-cpp-sys-2 = { git = "https://github.com/utilityai/llama-cpp-rs.git", rev = "6ab83db" }
llama-cpp-2 = { git = "https://github.com/utilityai/llama-cpp-rs.git", rev = "6ab83db" }
lazy_static = "1.5.0"
minijinja-contrib = { version = "2.7.0", features = ["pycompat"] }
serde_json = "1.0"

[target.'cfg(target_os = "ios")'.dependencies]
llama-cpp-2 = { git = "https://github.com/utilityai/llama-cpp-rs.git", rev = "6ab83db", features = ["metal"] }

[target.'cfg(all(not(target_os = "macos"), not(target_os = "ios")))'.dependencies]
llama-cpp-2 = { git = "https://github.com/utilityai/llama-cpp-rs.git", rev = "6ab83db", features = ["vulkan"] }

[target.aarch64-apple-ios]
rustflags = [
    "-C", "link-arg=-mios-version-min=14.0",
    "-C", "link-arg=-target", "-C", "link-arg=arm64-apple-ios",
    "-C", "link-arg=-fapple-link-rtlib",
    "-C", "link-arg=-L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/16/lib/darwin/ios",
    "-C", "link-arg=-lclang_rt.ios",
    "-C", "link-arg=-framework", "-C", "link-arg=Metal",
    "-C", "link-arg=-framework", "-C", "link-arg=MetalKit",
    "-C", "link-arg=-framework", "-C", "link-arg=Foundation"
]
